baseURL: "https://ki-vorlesung.github.io/lecture/"

languageCode: "de-DE"
metaDataFormat: "yaml"
theme: "hugo-theme-learn"

contentDir: content
publishDir: docs

params:
  editURL: "https://github.com/KI-Vorlesung/Lecture/edit/master/markdown/"
  author: "cagix"
  themeVariant: "green"
  titleSeparator: " "
  showVisitedLinks: true
  disableBreadcrumb: false
  disableInlineCopyToClipBoard: true
  disableNextPrev: true
  disableSearch: true
  disableLandingPageButton: true
  disableMermaid: true

menu:
  shortcuts:
  - name: "<i class='fas fa-bookmark'></i> Fahrplan"
    url: "/orga/fahrplan"
    weight: 10
  - name: "<i class='fas fa-bookmark'></i> Praktikum"
    url: "/praktikum"
    weight: 10
  - name: "<i class='fas fa-bookmark'></i> Note/Credits"
    url: "/orga/note_und_credits"
    weight: 20
  - name: "<i class='fas fa-bookmark'></i> Syllabus"
    url: "/orga/syllabus"
    weight: 30
  - name: "<i class='fas fa-bookmark'></i> Reading"
    url: "/orga/reading"
    weight: 40

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: false
    privacyEnhanced: true
